# Fetching Historical Data using yfinance
I am using the top 25 aerospace and defense companies from Yahoo Finance.

In [ ]:
# import necessary libraries
import numpy as np
import pandas as pd
import yfinance as yf
from itertools import combinations

ticker_list = ['GE', 'RTX', 'BA', 'LMT', 'TDG', 'GD', 'HWM', 'NOC', 'AXON', 'LHX', 'HEI-A', 'RKLB', 'CW', 'TXT', 'WWD', 'BWXT', 'DRS', 'SARO', 'HII', 'KTOS', 'AVAV', 'LOAR', 'MOG-A', 'ACHR', 'HXL']
data = yf.download(ticker_list, period='1y')

/var/folders/sx/1hm8tkl152z03tg5g8wfh9y40000gn/T/ipykernel_81967/341298470.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_list, period='1y')
[*********************100%***********************]  25 of 25 completed

In [11]:
# create a pandas DataFrame of just the closing prices
data_close = pd.DataFrame(data['Close'])

In [5]:
data_close

Ticker,ACHR,AVAV,AXON,BA,BWXT,CW,DRS,GD,GE,HEI-A,...,LMT,LOAR,MOG-A,NOC,RKLB,RTX,SARO,TDG,TXT,WWD
Date,,,,,,,,,,,,,,,,,,,,,
2024-07-22,4.60,168.419998,316.760010,178.899994,103.263092,280.676941,28.623581,285.228394,161.717468,178.251724,...,462.394928,59.799999,189.318436,430.539185,5.340000,101.635712,NaN,1189.477295,91.727158,178.792557
2024-07-23,4.56,171.520004,319.549988,186.479996,104.769135,283.370605,27.787855,288.411621,170.898285,182.816879,...,488.408875,62.169998,193.692764,434.666656,5.400000,102.811028,NaN,1219.104126,92.036835,182.759338
2024-07-24,4.38,170.309998,313.109985,180.070007,99.101654,278.551971,27.648569,278.822754,161.260422,180.219635,...,501.961426,59.849998,189.288605,434.489777,5.210000,102.673912,NaN,1179.655396,90.028877,176.138107
2024-07-25,4.40,169.940002,310.809998,184.350006,97.823502,278.122986,28.026634,285.003143,163.615234,182.177551,...,508.002106,62.259998,193.245392,462.448792,5.250000,111.136215,NaN,1163.497070,91.197685,178.295456
2024-07-26,4.69,173.820007,310.589996,186.889999,98.229736,279.659363,28.354954,284.435028,168.722305,184.704880,...,511.314667,62.770000,196.953613,472.010864,5.400000,111.606339,NaN,1169.596680,91.966911,182.063400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-07-16,12.09,268.920013,742.770020,229.899994,139.850006,481.790009,48.009998,300.000000,266.179993,251.289993,...,471.470001,75.839996,186.929993,519.700012,47.689999,150.169998,30.270,1574.599976,84.139999,253.639999
2025-07-17,13.40,278.559998,745.859985,231.000000,142.339996,484.100006,48.330002,300.089996,260.279999,251.910004,...,469.200012,78.050003,192.910004,523.830017,51.330002,151.500000,30.770,1595.250000,85.360001,257.420013
2025-07-18,13.29,274.029999,756.090027,229.339996,142.949997,487.880005,48.130001,298.980011,263.269989,253.130005,...,463.959991,76.150002,192.009995,519.039978,51.389999,151.500000,30.400,1597.300049,85.000000,258.429993
2025-07-21,11.85,272.179993,751.549988,229.320007,140.360001,480.059998,46.790001,297.049988,262.859985,251.460007,...,460.529999,75.339996,190.699997,515.289978,47.189999,151.559998,29.760,1583.670044,84.750000,254.149994
2025-07-22,11.07,263.214996,726.210022,228.960007,140.789993,475.820007,46.384998,297.514099,260.075012,249.669998,...,415.630005,74.449997,188.994995,565.049988,47.369999,149.285004,29.025,1574.410034,86.160004,252.050003

In [13]:
# create combinations of the stocks

In [12]:
# export the data to a csv file
data_close.to_csv('/Users/ashleytran/Desktop/URE25/pairs-trading/data/stock_data.csv')