# Fetching Historical Data using yfinance
I am using the top 25 aerospace and defense companies from Yahoo Finance.

In [24]:
# import necessary libraries
import numpy as np
import pandas as pd
import yfinance as yf
from itertools import combinations

ticker_list = ['GE', 'RTX', 'BA', 'LMT', 'TDG', 'GD', 'HWM', 'NOC', 'AXON', 'LHX', 'HEI-A', 'RKLB', 'CW', 'TXT', 'WWD', 'BWXT', 'DRS', 'SARO', 'HII', 'KTOS', 'AVAV', 'LOAR', 'MOG-A', 'ACHR', 'HXL']
data = yf.download(ticker_list, start='2024-06-16', end='2025-06-16')

/var/folders/sx/1hm8tkl152z03tg5g8wfh9y40000gn/T/ipykernel_81967/1789393548.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker_list, start='2024-06-16', end='2025-06-16')
[*********************100%***********************]  25 of 25 completed

In [25]:
# create a pandas DataFrame of just the closing prices
data_close = pd.DataFrame(data['Close'])

In [26]:
data_close

Ticker,ACHR,AVAV,AXON,BA,BWXT,CW,DRS,GD,GE,HEI-A,...,LMT,LOAR,MOG-A,NOC,RKLB,RTX,SARO,TDG,TXT,WWD
Date,,,,,,,,,,,,,,,,,,,,,
2024-06-17,3.17,215.110001,297.170013,178.389999,90.372543,270.241669,24.673784,286.360077,161.910400,179.169540,...,447.215271,59.389999,160.875443,422.362762,4.340000,102.321320,NaN,1249.204590,85.833122,183.455246
2024-06-18,3.06,219.309998,293.519989,174.990005,91.700249,277.943451,25.977119,290.424072,163.636337,179.848389,...,448.179840,59.759998,164.166122,418.480896,4.910000,102.615143,NaN,1268.687378,85.873085,184.429520
2024-06-20,3.12,203.589996,293.140015,176.300003,91.640793,275.549072,25.061800,292.012634,163.666092,177.981522,...,454.356934,58.389999,164.802383,426.981659,4.800000,102.908981,NaN,1259.395996,86.172775,183.156982
2024-06-21,3.66,189.479996,291.149994,176.559998,92.156021,274.361877,25.867676,290.667725,162.912247,178.430771,...,455.584534,56.200001,167.029312,424.632874,5.010000,103.437866,NaN,1251.269287,86.652283,182.093231
2024-06-24,3.74,190.490005,292.700012,179.100006,93.156738,274.740997,25.608999,290.940582,159.242126,178.410797,...,459.394104,58.000000,163.887772,423.237427,4.830000,99.862946,NaN,1257.861572,87.391541,179.737030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-06-09,11.26,195.720001,783.799988,217.509995,132.619995,459.826721,44.540001,275.894775,251.043396,238.009552,...,480.829987,89.209999,185.100006,491.359985,29.639999,140.979996,30.75,1460.060059,77.060188,234.559998
2025-06-10,11.38,189.619995,762.659973,215.729996,131.710007,456.308502,43.540001,275.954468,241.647110,234.081390,...,476.899994,82.919998,181.029999,488.799988,27.170000,138.520004,30.77,1433.040039,77.829987,229.720001
2025-06-11,12.17,189.520004,778.359985,214.000000,135.800003,471.470795,44.639999,274.422302,245.161987,235.210876,...,456.600006,83.919998,178.570007,488.459991,27.360001,141.809998,30.74,1429.619995,76.780258,233.050003
2025-06-12,11.73,190.119995,775.200012,203.750000,137.779999,473.949554,45.290001,278.501404,239.640045,237.429825,...,469.269989,84.389999,180.500000,497.130005,26.400000,140.979996,30.77,1435.839966,77.780006,234.949997
2025-06-13,9.99,195.100006,780.630005,200.320007,138.070007,473.080017,46.070000,281.555725,236.254990,238.679245,...,486.450012,83.410004,181.520004,516.719971,25.410000,145.690002,30.41,1439.609985,77.379997,232.059998

In [23]:
# create combinations of the stocks
pair_list = combinations(ticker_list, 2)
pair_data = []

In [27]:
# export the data to a csv file
data_close.to_csv('/Users/ashleytran/Desktop/URE25/pairs-trading/data/stock_data.csv')